version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: beer-is-good
      MYSQL_DATABASE: beer
      TZ: America/Sao_Paulo
    ports:
      - 3320:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

